doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Core:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Core/Domain'
                prefix: 'App\Core\Domain'
                alias: App
            Applicants:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Applicants/Domain'
                prefix: 'App\Applicants\Domain'
                alias: App
            Offers:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Offers/Domain'
                prefix: 'App\Offers\Domain'
                alias: App